const express = require("express");
const bodyParser = require("body-parser");
const cors = require("cors");
const dotenv = require("dotenv");
const connectDB = require("./config/db");
dotenv.config();
connectDB();
const app = express();
app.use(cors());
app.use(bodyParser.json());
app.use("/api/faqs", require("./routes/faqRoutes"));
module.exports = app;
